using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.InteropServices;
const ulong SiteRva = 0x133CFDFF, OriginalTargetRva = 0xA0CF70; const uint Op = 8, ReadAccess = 0x10, WriteAccess = 0x20, Query = 0x400, Commit = 0x1000, Reserve = 0x2000, Release = 0x8000, Rw = 4, Rx = 0x40, Rwx = 0x40; const int F5 = 0x74, F6 = 0x75, F12 = 0x7B;
using Process game = Process.GetProcessesByName("GRW").SingleOrDefault() ?? throw new InvalidOperationException("Exactly one GRW process must run."); ulong b = (ulong)(game.MainModule?.BaseAddress.ToInt64() ?? 0), site = b + SiteRva, target = b + OriginalTargetRva, cave = 0; byte[] original = new byte[5]; original[0] = 0xE8; BitConverter.GetBytes(Rel(site, 5, target)).CopyTo(original, 1); nint h = OpenProcess(Op | ReadAccess | WriteAccess | Query, false, game.Id); if (h == 0) throw new Win32Exception(Marshal.GetLastWin32Error()); bool installed = false; string log = Path.Combine(AppContext.BaseDirectory, "speed-scalar.log"); File.WriteAllText(log, "");
try { byte[] cur = R(h, site, 5); if (!cur.SequenceEqual(original)) throw new InvalidOperationException($"Unexpected bytes {Convert.ToHexString(cur)} expected {Convert.ToHexString(original)}"); cave = Near(h, site); const int Slot = 64; byte[] code = new byte[68]; int p = 0; code[p++] = 0xF3; code[p++] = 0x0F; code[p++] = 0x11; code[p++] = 0x3D; BitConverter.GetBytes(checked((int)((long)(cave + Slot) - (long)(cave + (ulong)p + 4)))).CopyTo(code, p); p += 4; code[p++] = 0xE9; BitConverter.GetBytes(Rel(cave + (ulong)p - 1, 5, target)).CopyTo(code, p); p += 4; W(h, cave, code); if (!VirtualProtectEx(h, (nint)cave, (nuint)code.Length, Rx, out _)) throw new Win32Exception(Marshal.GetLastWin32Error()); byte[] redirect = new byte[5]; redirect[0] = 0xE8; BitConverter.GetBytes(Rel(site, 5, cave)).CopyTo(redirect, 1); Patch(h, site, redirect); installed = true; void Restore() { if (!installed) return; try { Patch(h, site, original); } catch { } installed = false; } AppDomain.CurrentDomain.ProcessExit += (_, _) => Restore(); Console.CancelKeyPress += (_, e) => { e.Cancel = true; Restore(); }; void Snap(string state) { float v = BitConverter.ToSingle(R(h, cave + Slot, 4)); string line = $"{DateTime.Now:HH:mm:ss.fff}\t{state}\txmm7={v.ToString("R", CultureInfo.InvariantCulture)}"; Console.WriteLine(line); File.AppendAllText(log, line + Environment.NewLine); } Console.WriteLine($"Scalar logger installed at 0x{site:X16}; F5 HIP, F6 ADS, F12 restore+exit."); bool x0 = false, y0 = false, z0 = false; while (true) { bool x = Down(F5), y = Down(F6), z = Down(F12); if (x && !x0) Snap("HIP"); if (y && !y0) Snap("ADS"); if (z && !z0) break; x0 = x; y0 = y; z0 = z; Thread.Sleep(20); } Restore(); return 0; } finally { if (installed) try { Patch(h, site, original); } catch { } if (cave != 0) VirtualFreeEx(h, (nint)cave, 0, Release); CloseHandle(h); }
static int Rel(ulong i, int n, ulong t) { long r = (long)t - ((long)i + n); if (r < int.MinValue || r > int.MaxValue) throw new InvalidOperationException("rel32"); return (int)r; }
static ulong Near(nint h, ulong s) { for (ulong d = 0x10000; d < 0x70000000; d += 0x10000) foreach (ulong a in new[] { (s + d) & ~0xFFFFUL, (s - d) & ~0xFFFFUL }) { nint p = VirtualAllocEx(h, (nint)a, 4096, Commit | Reserve, Rw); if (p != 0) return (ulong)p.ToInt64(); } throw new Win32Exception(Marshal.GetLastWin32Error()); }
static byte[] R(nint h, ulong a, int n) { byte[] b = new byte[n]; if (!ReadProcessMemory(h, (nint)a, b, (nuint)n, out nuint r) || r != (nuint)n) throw new Win32Exception(Marshal.GetLastWin32Error()); return b; }
static void W(nint h, ulong a, byte[] b) { if (!WriteProcessMemory(h, (nint)a, b, (nuint)b.Length, out nuint w) || w != (nuint)b.Length) throw new Win32Exception(Marshal.GetLastWin32Error()); }
static void Patch(nint h, ulong a, byte[] b) { if (!VirtualProtectEx(h, (nint)a, (nuint)b.Length, Rwx, out uint o)) throw new Win32Exception(Marshal.GetLastWin32Error()); try { W(h, a, b); FlushInstructionCache(h, (nint)a, (nuint)b.Length); } finally { VirtualProtectEx(h, (nint)a, (nuint)b.Length, o, out _); } }
static bool Down(int k) => (GetAsyncKeyState(k) & 0x8000) != 0;
[DllImport("kernel32.dll", SetLastError = true)] static extern nint OpenProcess(uint a, bool i, int p); [DllImport("kernel32.dll", SetLastError = true)] static extern nint VirtualAllocEx(nint p, nint a, nuint s, uint t, uint r); [DllImport("kernel32.dll", SetLastError = true)] static extern bool VirtualFreeEx(nint p, nint a, nuint s, uint t); [DllImport("kernel32.dll", SetLastError = true)] static extern bool VirtualProtectEx(nint p, nint a, nuint s, uint n, out uint o); [DllImport("kernel32.dll", SetLastError = true)] static extern bool ReadProcessMemory(nint p, nint a, [Out] byte[] b, nuint s, out nuint r); [DllImport("kernel32.dll", SetLastError = true)] static extern bool WriteProcessMemory(nint p, nint a, byte[] b, nuint s, out nuint w); [DllImport("kernel32.dll", SetLastError = true)] static extern bool FlushInstructionCache(nint p, nint a, nuint s); [DllImport("kernel32.dll")] static extern bool CloseHandle(nint h); [DllImport("user32.dll")] static extern short GetAsyncKeyState(int k);
