<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>GRWAnalogueMovement</AssemblyName>
    <RootNamespace>GRWAnalogueMovement</RootNamespace>
    <AssemblyTitle>Better Movement for KBM - GRW</AssemblyTitle>
    <Product>Better Movement for KBM - GRW</Product>
    <Description>Better Movement for KBM - GRW</Description>
    <Version>1.2.0</Version>
    <FileVersion>1.2.0.0</FileVersion>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
  </PropertyGroup>
</Project>
